// <auto-generated />
using System;
using HortiDot.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HortiDot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231118140009_AttModelPedidos02")]
    partial class AttModelPedidos02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HortiDot.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompradorIdID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FornecedorIdID")
                        .HasColumnType("integer");

                    b.Property<int>("StatusPedidos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompradorIdID");

                    b.HasIndex("FornecedorIdID");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("HortiDot.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("HortiDot.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pedidos")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoDeUsuario")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Usuários");
                });

            modelBuilder.Entity("HortiDot.Models.Pedido", b =>
                {
                    b.HasOne("HortiDot.Models.Usuario", "CompradorId")
                        .WithMany()
                        .HasForeignKey("CompradorIdID");

                    b.HasOne("HortiDot.Models.Usuario", "FornecedorId")
                        .WithMany()
                        .HasForeignKey("FornecedorIdID");

                    b.Navigation("CompradorId");

                    b.Navigation("FornecedorId");
                });

            modelBuilder.Entity("HortiDot.Models.Produto", b =>
                {
                    b.HasOne("HortiDot.Models.Pedido", null)
                        .WithMany("ListaProdutos")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("HortiDot.Models.Pedido", b =>
                {
                    b.Navigation("ListaProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
